POST http://localhost:9114/SV6/BillsTable/Mail/WithImage
Content-Type: application/json

{
  "BuyerName": "",
  "BuyerAddress": "",
  "BuyerGST": "",
  "InvoiceNo": "",
  "InvoiceDate": "",
  "InvoiceStateCode": ""
}