POST http://localhost:9114/SV6/BillItemsTable/SubTableOnObj/Insert/WithUuIdAndDT/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "ItemName": "",
  "Rate": "",
  "Qty": "",
  "Amount": "",
  "FK": ""
}